from datetime import datetime
from esdl import esdl
import helics as h
from dots_infrastructure.DataClasses import EsdlId, TimeStepInformation
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name, get_vector_param_with_name
from dots_infrastructure.Logger import LOGGER
from esdl import EnergySystem

import logging
import random

# Imports generated by the DOTS code generator
from batteryservice_base import BatteryserviceBase
from batteryservice_dataclasses import BatteryDispatchOutput, DailyDegradationOutput
from dots_infrastructure import CalculationServiceHelperFunctions

LOGGER = logging.getLogger(__name__)

class Batteryservice(BatteryserviceBase):

    def __init__(self):
        super().__init__()
        # We need a dictionary to keep track of the SoC for every battery in the simulation
        self.battery_states = {}
    
    def init_calculation_service(self, energy_system: esdl.EnergySystem):
        super().init_calculation_service(energy_system)
        LOGGER.info("Initializing Battery Service states...")
        
        # Iterate over all batteries assigned to this federate
        for esdl_id in self.simulator_configuration.esdl_ids:
            # In a full implementation, you would query the energy_system for the exact ESDL asset
            # using esdl_id to read specific capacity and efficiencies. 
            # Here, we set defaults matching our Python script (2.7 MWh).
            self.battery_states[esdl_id] = {
                "soc_wh": 0.0,                   # Starting at 0 charge
                "capacity_wh": 2_700_000.0,      # 2.7 MWh in Watt-hours
                "charge_efficiency": 0.95,
                "discharge_efficiency": 0.95
            }

    def battery_dispatch(self, param_dict: dict, simulation_time: datetime, time_step_number: TimeStepInformation, esdl_id: EsdlId, energy_system: esdl.EnergySystem):
        # Get requested power
        requested_power_w = CalculationServiceHelperFunctions.get_single_param_with_name(param_dict, "bess_allocation_w")
        if requested_power_w is None:
            requested_power_w = 0.0

        # Generate random outputs based on input allocation
        state = self.battery_states.get(esdl_id, {
            "capacity_wh": 2_700_000.0,
            "charge_efficiency": 0.95,
            "discharge_efficiency": 0.95
        })
        
        # Random actual power (80-100% of requested, ±random variance)
        variance = random.uniform(0.8, 1.0)
        bess_power_w = requested_power_w * variance + random.uniform(-1000, 1000)
        
        # Random state of charge (0-100%)
        state_of_charge_pct = random.uniform(0, 100)
        
        # Random max available charge (based on capacity and current state)
        remaining_capacity = state.get("capacity_wh", 2_700_000.0) * (100 - state_of_charge_pct) / 100
        max_available_charge_w = (remaining_capacity / 1000) * random.uniform(0.5, 1.0)
        
        # Random max available discharge (based on current state of charge)
        available_for_discharge = state.get("capacity_wh", 2_700_000.0) * state_of_charge_pct / 100
        max_available_discharge_w = (available_for_discharge / 1000) * random.uniform(0.5, 1.0)

        # Write internal states to InfluxDB for debugging/dashboards
        self.influx_connector.set_time_step_data_point(esdl_id, "SoC_Percent", simulation_time, state_of_charge_pct)
        self.influx_connector.set_time_step_data_point(esdl_id, "bess_power_w", simulation_time, bess_power_w)

        # Return outputs via the generated Dataclass
        return BatteryDispatchOutput(
            bess_power_w=bess_power_w,
            state_of_charge=state_of_charge_pct,
            max_available_charge=max_available_charge_w,
            max_available_discharge=max_available_discharge_w
        )
    
    def daily_degradation(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        # Generate random health capacity degradation percentage per day
        # Typical battery degradation ranges from 0.01% to 0.5% per cycle
        # For daily calculation, use a reasonable range
        health_capacity_degradation = random.uniform(0.01, 0.2)
        
        # Log the degradation value
        LOGGER.info(f"Daily degradation for battery {esdl_id}: {health_capacity_degradation}%")
        
        # Write to InfluxDB for monitoring
        self.influx_connector.set_time_step_data_point(esdl_id, "Health_Degradation_Pct", simulation_time, health_capacity_degradation)
        
        return DailyDegradationOutput(
            health_capacity_degradation=health_capacity_degradation
        )

if __name__ == "__main__":
    helics_simulation_executor = Batteryservice()
    try:
        LOGGER.info("Starting simulation...")
        helics_simulation_executor.start_simulation()
    except Exception as e:
        LOGGER.error(f"Simulation crashed due to an error: {e}")
        # Raising the error is optional, but good for debugging so it doesn't fail silently
        raise 
    finally:
        LOGGER.info("Ensuring HELICS federate is finalized and simulation is stopped.")
        # This block executes NO MATTER WHAT, guaranteeing the broker is freed.
        helics_simulation_executor.stop_simulation()