from datetime import datetime
from esdl import esdl
import helics as h
from dots_infrastructure.DataClasses import EsdlId, TimeStepInformation
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name, get_vector_param_with_name
from dots_infrastructure.Logger import LOGGER
from esdl import EnergySystem

import logging
import random

# Imports generated by the DOTS code generator
from batteryservice_base import BatteryserviceBase
from batteryservice_dataclasses import BatteryDispatchOutput, DailyDegradationOutput
from dots_infrastructure import CalculationServiceHelperFunctions

LOGGER = logging.getLogger(__name__)

class Batteryservice(BatteryserviceBase):

    def __init__(self):
        super().__init__()
        # We need a dictionary to keep track of the SoC for every battery in the simulation
        self.battery_states = {}
    
    def init_calculation_service(self, energy_system: esdl.EnergySystem):
        super().init_calculation_service(energy_system)
        LOGGER.info("Initializing Battery Service states...")
        
        # Iterate over all batteries assigned to this federate
        for esdl_id in self.simulator_configuration.esdl_ids:
            capacity_wh = 2_700_000.0
            charge_eff = 0.95
            discharge_eff = 0.95
            
            # Query the energy_system via our base class esdl_obj_mapping
            esdl_battery = self.esdl_obj_mapping.get(esdl_id)
            max_charge_w = 2_700_000.0
            max_discharge_w = 2_700_000.0
            if esdl_battery is not None:
                if getattr(esdl_battery, 'capacity', 0.0) != 0.0:
                    # ESDL capacity is defined in kWh, script works with Wh
                    capacity_wh = float(esdl_battery.capacity) * 1000.0
                    max_charge_w = capacity_wh
                    max_discharge_w = capacity_wh
                if getattr(esdl_battery, 'chargeEfficiency', 0.0) != 0.0:
                    charge_eff = float(esdl_battery.chargeEfficiency)
                if getattr(esdl_battery, 'dischargeEfficiency', 0.0) != 0.0:
                    discharge_eff = float(esdl_battery.dischargeEfficiency)
                if getattr(esdl_battery, 'maxChargeRate', 0.0) != 0.0:
                    max_charge_w = float(esdl_battery.maxChargeRate)
                if getattr(esdl_battery, 'maxDischargeRate', 0.0) != 0.0:
                    max_discharge_w = float(esdl_battery.maxDischargeRate)
            
            self.battery_states[esdl_id] = {
                "soc_wh": 0.0,                   # Starting at 0 charge
                "capacity_wh": capacity_wh,
                "max_charge_power_w": max_charge_w,
                "max_discharge_power_w": max_discharge_w,
                "charge_efficiency": charge_eff,
                "discharge_efficiency": discharge_eff,
                "daily_throughput_wh": 0.0       # Track daily energy cycled
            }

    def battery_dispatch(self, param_dict: dict, simulation_time: datetime, time_step_number: TimeStepInformation, esdl_id: EsdlId, energy_system: esdl.EnergySystem):
        # Get requested power
        requested_power_w = CalculationServiceHelperFunctions.get_single_param_with_name(param_dict, "bess_allocation_w")
        if requested_power_w is None:
            requested_power_w = 0.0

        # Generate realistic outputs based on input allocation
        state = self.battery_states.get(esdl_id)
        if not state:
            # Fallback if state was not initialized
            capacity_wh = 2_700_000.0
            charge_eff = 0.95
            discharge_eff = 0.95
            max_charge_w = 2_700_000.0
            max_discharge_w = 2_700_000.0
            
            esdl_battery = self.esdl_obj_mapping.get(esdl_id)
            if esdl_battery is not None:
                if getattr(esdl_battery, 'capacity', 0.0) != 0.0:
                    capacity_wh = float(esdl_battery.capacity) * 1000.0
                    max_charge_w = capacity_wh
                    max_discharge_w = capacity_wh
                if getattr(esdl_battery, 'chargeEfficiency', 0.0) != 0.0:
                    charge_eff = float(esdl_battery.chargeEfficiency)
                if getattr(esdl_battery, 'dischargeEfficiency', 0.0) != 0.0:
                    discharge_eff = float(esdl_battery.dischargeEfficiency)
                if getattr(esdl_battery, 'maxChargeRate', 0.0) != 0.0:
                    max_charge_w = float(esdl_battery.maxChargeRate)
                if getattr(esdl_battery, 'maxDischargeRate', 0.0) != 0.0:
                    max_discharge_w = float(esdl_battery.maxDischargeRate)

            state = {
                "soc_wh": 0.0,
                "capacity_wh": capacity_wh,
                "max_charge_power_w": max_charge_w,
                "max_discharge_power_w": max_discharge_w,
                "charge_efficiency": charge_eff,
                "discharge_efficiency": discharge_eff,
                "daily_throughput_wh": 0.0
            }
            self.battery_states[esdl_id] = state
            
        if "daily_throughput_wh" not in state:
            state["daily_throughput_wh"] = 0.0
            
        time_step_hours = 900.0 / 3600.0 # 900 seconds dispatch from input.json
        capacity_wh = state["capacity_wh"]
        current_soc_wh = state["soc_wh"]
        charge_eff = state["charge_efficiency"]
        discharge_eff = state["discharge_efficiency"]
        
        # Max power limits specifically configured
        max_charge_pwr_w = state["max_charge_power_w"]
        max_discharge_pwr_w = state["max_discharge_power_w"]
        
        # Calculate maximum limits based on current SoC
        remaining_capacity_wh = capacity_wh - current_soc_wh
        
        # Max W that can be drawn from the network to charge the battery
        max_available_charge_w = min(max_charge_pwr_w, remaining_capacity_wh / (charge_eff * time_step_hours))
        
        # Max W that can be supplied to the network by discharging
        max_available_discharge_w = min(max_discharge_pwr_w, (current_soc_wh * discharge_eff) / time_step_hours)
        
        bess_power_w = 0.0
        if requested_power_w > 0:
            # Charging
            bess_power_w = min(requested_power_w, max_available_charge_w)
            energy_added_wh = bess_power_w * charge_eff * time_step_hours
            state["soc_wh"] += energy_added_wh
            state["daily_throughput_wh"] += energy_added_wh
        elif requested_power_w < 0:
            # Discharging
            requested_discharge_w = -requested_power_w
            actual_discharge_w = min(requested_discharge_w, max_available_discharge_w)
            bess_power_w = -actual_discharge_w
            energy_removed_wh = actual_discharge_w / discharge_eff * time_step_hours
            state["soc_wh"] -= energy_removed_wh
            state["daily_throughput_wh"] += energy_removed_wh

        # Ensure SoC remains strictly within boundaries to overcome float inaccuracies
        state["soc_wh"] = max(0.0, min(capacity_wh, state["soc_wh"]))
        state_of_charge_pct = (state["soc_wh"] / capacity_wh) * 100.0
        
        # Recalculate max available for output reporting (after this time step)
        remaining_capacity_wh = capacity_wh - state["soc_wh"]
        reported_max_charge_w = min(max_charge_pwr_w, remaining_capacity_wh / (charge_eff * time_step_hours))
        reported_max_discharge_w = min(max_discharge_pwr_w, (state["soc_wh"] * discharge_eff) / time_step_hours)

        # Write internal states to InfluxDB for debugging/dashboards
        self.influx_connector.set_time_step_data_point(esdl_id, "SoC_Percent", simulation_time, state_of_charge_pct)
        self.influx_connector.set_time_step_data_point(esdl_id, "bess_power_w", simulation_time, bess_power_w)

        # Return outputs via the generated Dataclass
        return BatteryDispatchOutput(
            bess_power_w=bess_power_w,
            state_of_charge=state_of_charge_pct,
            max_available_charge=reported_max_charge_w,
            max_available_discharge=reported_max_discharge_w
        )
    
    def daily_degradation(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        state = self.battery_states.get(esdl_id)
        
        if not state:
            return DailyDegradationOutput(health_capacity_degradation=0.0)
            
        # Calendar aging: ~0.005% per day
        calendar_aging_pct = 0.005
        
        # Cycle aging: ~0.02% per equivalent full cycle
        throughput_wh = state.get("daily_throughput_wh", 0.0)
        capacity_wh = state.get("capacity_wh", 2_700_000.0)
        
        equivalent_full_cycles = 0.0
        if capacity_wh > 0:
            # One equivalent full cycle is one full charge and one full discharge (2 * capacity)
            equivalent_full_cycles = throughput_wh / (2.0 * capacity_wh)
            
        cycle_aging_pct = equivalent_full_cycles * 0.02
        
        health_capacity_degradation = calendar_aging_pct + cycle_aging_pct
        
        # Reset daily throughput for the next day
        state["daily_throughput_wh"] = 0.0
        
        # Apply degradation to max capacity for real simulation
        state["capacity_wh"] *= (1.0 - (health_capacity_degradation / 100.0))
        
        # Log the degradation value
        LOGGER.info(f"Daily degradation for battery {esdl_id}: {health_capacity_degradation:.5f}% (Cycles: {equivalent_full_cycles:.2f})")
        
        # Write to InfluxDB for monitoring
        self.influx_connector.set_time_step_data_point(esdl_id, "Health_Degradation_Pct", simulation_time, health_capacity_degradation)
        
        return DailyDegradationOutput(
            health_capacity_degradation=health_capacity_degradation
        )

if __name__ == "__main__":
    helics_simulation_executor = Batteryservice()
    try:
        LOGGER.info("Starting simulation...")
        helics_simulation_executor.start_simulation()
    except Exception as e:
        LOGGER.error(f"Simulation crashed due to an error: {e}")
        # Raising the error is optional, but good for debugging so it doesn't fail silently
        raise 
    finally:
        LOGGER.info("Ensuring HELICS federate is finalized and simulation is stopped.")
        # This block executes NO MATTER WHAT, guaranteeing the broker is freed.
        helics_simulation_executor.stop_simulation()