from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, Battery
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated, DO NOT edit this file!

class BatteryserviceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, Battery]= {}

        
        # Calculation: battery_dispatch
        self.battery_dispatch_period_seconds = 900
        battery_dispatch_inputs = [
        
            SubscriptionDescription(esdl_type="ElectricityNetwork", 
                                    input_name="bess_allocation_w", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
        ]
        battery_dispatch_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="Battery",
                                    output_name="actual_power_w",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
            PublicationDescription(global_flag=True, 
                                    esdl_type="Battery",
                                    output_name="state_of_charge_wh",
                                    output_unit="Wh", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        battery_dispatch_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="battery_dispatch", 
            inputs=battery_dispatch_inputs, 
            outputs=battery_dispatch_outputs, 
            calculation_function=self.battery_dispatch
        )
        self.add_calculation(battery_dispatch_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), Battery)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def battery_dispatch(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    