from datetime import datetime
from esdl import esdl
import helics as h
from dots_infrastructure.DataClasses import EsdlId, TimeStepInformation
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name, get_vector_param_with_name
from dots_infrastructure.Logger import LOGGER
from esdl import EnergySystem

import logging

# Imports generated by the DOTS code generator
from batteryservice_base import BatteryserviceBase
from batteryservice_dataclasses import BatteryDispatchOutput
from dots_infrastructure import CalculationServiceHelperFunctions

LOGGER = logging.getLogger(__name__)

class Batteryservice(BatteryserviceBase):

    def __init__(self):
        super().__init__()
        # We need a dictionary to keep track of the SoC for every battery in the simulation
        self.battery_states = {}
    
    def init_calculation_service(self, energy_system: esdl.EnergySystem):
        super().init_calculation_service(energy_system)
        LOGGER.info("Initializing Battery Service states...")
        
        # Iterate over all batteries assigned to this federate
        for esdl_id in self.simulator_configuration.esdl_ids:
            # In a full implementation, you would query the energy_system for the exact ESDL asset
            # using esdl_id to read specific capacity and efficiencies. 
            # Here, we set defaults matching our Python script (2.7 MWh).
            self.battery_states[esdl_id] = {
                "soc_wh": 0.0,                   # Starting at 0 charge
                "capacity_wh": 2_700_000.0,      # 2.7 MWh in Watt-hours
                "charge_efficiency": 0.95,
                "discharge_efficiency": 0.95
            }

    def battery_dispatch(self, param_dict: dict, simulation_time: datetime, time_step_number: TimeStepInformation, esdl_id: EsdlId, energy_system: esdl.EnergySystem):
        # 1. Retrieve current state and input request
        state = self.battery_states[esdl_id]
        
        # Get requested power (Default to 0 if no input is received yet)
        requested_power_w = CalculationServiceHelperFunctions.get_single_param_with_name(param_dict, "bess_allocation_w")
        if requested_power_w is None:
            requested_power_w = 0.0

        # 2. Physics Calculation
        dt_hours = 0.25
        requested_energy_wh = requested_power_w * dt_hours
        
        actual_power_w = 0.0

        if requested_energy_wh > 0:
            # CHARGING: Apply charge efficiency (less energy actually reaches the chemical storage)
            energy_to_store_wh = requested_energy_wh * state["charge_efficiency"]
            
            # Constraint: Cannot exceed maximum capacity
            actual_stored_wh = min(energy_to_store_wh, state["capacity_wh"] - state["soc_wh"])
            
            # Update state
            state["soc_wh"] += actual_stored_wh
            
            # Calculate power drawn from the grid to achieve this storage
            actual_power_w = (actual_stored_wh / state["charge_efficiency"]) / dt_hours

        elif requested_energy_wh < 0:
            # DISCHARGING: Apply discharge efficiency (must pull more energy from storage to meet grid demand)
            energy_needed_from_storage_wh = abs(requested_energy_wh) / state["discharge_efficiency"]
            
            # Constraint: Cannot drop below 0 SoC
            actual_pulled_wh = min(energy_needed_from_storage_wh, state["soc_wh"])
            
            # Update state
            state["soc_wh"] -= actual_pulled_wh
            
            # Calculate power actually delivered to the grid (Negative value)
            actual_power_w = -1 * (actual_pulled_wh * state["discharge_efficiency"]) / dt_hours

        # 3. Write internal states to InfluxDB for debugging/dashboards
        self.influx_connector.set_time_step_data_point(esdl_id, "SoC_Wh", simulation_time, state["soc_wh"])

        # 4. Return outputs via the generated Dataclass
        return BatteryDispatchOutput(
            actual_power_w=actual_power_w,
            state_of_charge_wh=state["soc_wh"]
        )

if __name__ == "__main__":
    helics_simulation_executor = Batteryservice()
    helics_simulation_executor.start_simulation()
    helics_simulation_executor.stop_simulation()